name: basic
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@4023961
        # execute Cypress using a custom test command
        with:
          # verifies the number of passing tests
          command: npm run expect
          # pass any specific variables to Cypress
          # to read using Cypress.env("lastName")
          env: lastName=Smith
        # when setting "plain" environment variables
        # if we want to pass Cypress to read them
        # we need to prefix them with "CYPRESS_"
        # https://on.cypress.io/environment-variables
        env:
          CYPRESS_firstName: Joe
