name: pr
# run this action on Push and on Pull Request
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          group: ${{ github.event.type }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
