name: install
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: yarn serve
          config-file: serve.json
